<h1>Импорт библиотек

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [3]:
import numpy as np

def sum_prod(X, V):
    '''
    X - матрицы (n, n)
    V - векторы (n, 1)
    Гарантируется, что len(X) == len(V)
    '''
    total = np.zeros_like(V[0])
    for i in range(len(X)):
        total += X[i] @ V[i]
    return total


X = [np.array([[1, 0], [0, 1]]), np.array([[2, 0], [0, 2]])]
V = [np.array([[1], [1]]), np.array([[1], [1]])]
print(sum_prod(X, V))

[[3]
 [3]]


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [4]:
import numpy as np

def binarize(M, threshold=0.5):
    return (M > threshold).astype(int)

M1 = np.array([[0.1, 0.6], [0.5, 0.7]])
print(binarize(M1))

[[0 1]
 [0 1]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [8]:
import numpy as np

def unique_rows(mat):
    unique = []
    for row in mat:
        unique.append(np.unique(row))
    return unique

def unique_columns(mat):
    unique = []
    for col in mat.T:
        unique.append(np.unique(col))
    return unique

mat = np.array([
    [1, 2, 2, 3],
    [4, 4, 5, 6],
    [7, 8, 7, 8]
])


print("Уникальные элементы по строкам:")
for i, uniques in enumerate(unique_rows(mat)):
    print(uniques)

print("\nУникальные элементы по столбцам:")
for i, uniques in enumerate(unique_columns(mat)):
    print(uniques)

Уникальные элементы по строкам:
[1 2 3]
[4 5 6]
[7 8]

Уникальные элементы по столбцам:
[1 4 7]
[2 4 8]
[2 5 7]
[3 6 8]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
pass

<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
import numpy as np

def chess(m, n, a, b):
    mat = np.empty((m, n), dtype=type(a))
    for i in range(m):
        for j in range(n):
            mat[i, j] = a if (i + j) % 2 == 0 else b
    return mat


print(chess(3, 3, 1, 0))

print(chess(2, 4, 'A', 'B'))


[[1 0 1]
 [0 1 0]
 [1 0 1]]
[['A' 'B' 'A' 'B']
 ['B' 'A' 'B' 'A']]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [ ]:
def draw_rectangle(a, b, m, n, rectangle_color, background_color):
    # Your code goes here
    pass

def draw_ellipse(a, b, m, n, ellipse_color, background_color):
    # Your code goes here
    pass




<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
# Your code goes here

<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
# Your code goes here